### ISSUE TITLE
Investigate the crashes in the workshop

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#37]
Happens when converting non-compatible values into numbers, from path and query parameter

https://www.twitch.tv/videos/174665157?t=02h32m00s

**Comment by benmerckx** [comment]
I've had it crash in the same way. Testing something like `@:get('/$id') function get(id: Int)` will bring down the server if you navigate to `/not-an-integer`.

**Comment by back2dos** [comment]
The problem is that path parts get parsed per implicit cast from `Stringly` which throws. Wrapping [the call](https://github.com/haxetink/tink_web/blob/pure/src/tink/web/macros/Routing.hx#L132) in try/catch would be the simplest solution. Would also catch other exceptions. Not sure that's a good thing, but maybe it's a start.

**Comment by back2dos** [comment]
Works now.
