### ISSUE TITLE
Generalized renderer

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#39]
Currently we have `@:html` and I wish to generalize it. Here are some quick ideas.

Add this meta to a route: `@:render(<content-type>, <function>)`
(or we could change/extend the current `@:produces` meta)

For each supported content type, the context will check one-by-one if the client accepts such type.
If yes, run the provided function, which should return a `OutgoingResponse` or anything that castable to it.

So the generated code should look sth like:

```haxe
runRoute(...)
  .next(function(result) {
    return
      if(context.accepts(<content-type1>)) <function1>(result)
      else if(context.accepts(<content-type2>)) <function1>(result)
      else new Error(415);
  })
  .next(function(rendered):OutgoingResponse return rendered) // cast it (or we can omit this step by explicity typing the function and do some macro magic)
  .next(function(res) return new OutgoingResponse(res.header.concat(new HeaderField(CONTENT_TYPE, matchedContentType), res.body));
```

We would also provide default implementations for json and urlencoded.

---

I think the major concern for me is that I think we should allow a route to be totally unaware of the http layer. (I think the reasoning is similar to that behind the `@:param(name in query)` thing)

And the route should return some pure data instead of some http responses. For example, I have recently implemented `TypedResponse` and realized that if I return such thing in my route and then my `@:html` function will look really silly.

Any ideas?

**Comment by back2dos** [comment]
Well, here's the thing I don't quite get: If the return type of the function is `{ bar: Int }`, what other sensible JSON representation could `{ bar: 5 }` have other than `{ "bar": 5 }`? And if you do apply some transformation, how will a tink_web client know how to reverse it and get back out something that is `{ bar: Int }` again?

The reason there's `@:html` renderers, is that for a given type structure, there's no canonical representation in HTML (although I find the idea tempting to try generating decent HTML just from a datatype). For JSON there is (as is for other serialization formats).

Could you share a concrete, real-world-like example, so that maybe I can somehow grasp the problem you're facing?

----

> I think the major concern for me is that I think we should allow a route to be totally unaware of the http layer. (I think the reasoning is similar to that behind the `@:param(name in query)` thing)

Oh yes, absolutely. But the `@:html` annotation is just as much *outside* the route as the `@:params`.

> And the route should return some pure data instead of some http responses. For example, I have recently implemented TypedResponse and realized that if I return such thing in my route and then my `@:html` function will look really silly.

What exactly makes it look silly? ^^

**Comment by kevinresol** [comment]
You are correct on the canonical representation which I haven't considered thoroughly.
I think the major thing I wanted is something to specify the response status code and header outside the route, which brings us back to #34 and #40 

> What exactly makes it look silly? ^^

Because I have already constructed an HTTP response but then I discard the http stuff (header) again.

**Comment by back2dos** [comment]
> Because I have already constructed an HTTP response but then I discard the http stuff (header) again.

Uhm, maybe we should run the renderer only on the body of the response?
